# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Numerical2' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Numerical2

  #pod 'Firebase/Core'
  #pod 'Firebase/AdMob'

  pod 'Fabric’
  pod 'Crashlytics'

  target 'Numerical2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Numerical2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
